import type { Flight } from '../types/flight';

export const mockFlights: Flight[] = [
  {
    id: '1',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '2024-01-15T08:00:00Z',
    arrivalTime: '2024-01-15T11:30:00Z',
    duration: '5h 30m',
    airline: 'American Airlines',
    airlineCode: 'AA',
    flightNumber: 'AA123',
    price: 299,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    aircraft: 'Boeing 737-800',
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'Los Angeles International Airport',
    departureTerminal: '8',
    arrivalTerminal: '4',
  },
  {
    id: '2',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '2024-01-15T10:30:00Z',
    arrivalTime: '2024-01-15T14:15:00Z',
    duration: '5h 45m',
    airline: 'Delta Air Lines',
    airlineCode: 'DL',
    flightNumber: 'DL456',
    price: 325,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    aircraft: 'Airbus A321',
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'Los Angeles International Airport',
    departureTerminal: '4',
    arrivalTerminal: '2',
  },
  {
    id: '3',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '2024-01-15T14:00:00Z',
    arrivalTime: '2024-01-15T18:45:00Z',
    duration: '6h 45m',
    airline: 'United Airlines',
    airlineCode: 'UA',
    flightNumber: 'UA789',
    price: 275,
    currency: 'USD',
    stops: 1,
    cabinClass: 'economy',
    aircraft: 'Boeing 737-900',
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'Los Angeles International Airport',
    departureTerminal: '7',
    arrivalTerminal: '7',
  },
  {
    id: '4',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '2024-01-15T16:30:00Z',
    arrivalTime: '2024-01-15T20:00:00Z',
    duration: '5h 30m',
    airline: 'JetBlue Airways',
    airlineCode: 'B6',
    flightNumber: 'B6 234',
    price: 245,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    aircraft: 'Airbus A320',
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'Los Angeles International Airport',
    departureTerminal: '5',
    arrivalTerminal: '5',
  },
  {
    id: '5',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '2024-01-15T19:00:00Z',
    arrivalTime: '2024-01-15T22:30:00Z',
    duration: '5h 30m',
    airline: 'Alaska Airlines',
    airlineCode: 'AS',
    flightNumber: 'AS567',
    price: 310,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    aircraft: 'Boeing 737-800',
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'Los Angeles International Airport',
    departureTerminal: '8',
    arrivalTerminal: '6',
  },
  {
    id: '6',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '2024-01-15T22:00:00Z',
    arrivalTime: '2024-01-16T01:30:00Z',
    duration: '5h 30m',
    airline: 'Spirit Airlines',
    airlineCode: 'NK',
    flightNumber: 'NK789',
    price: 180,
    currency: 'USD',
    stops: 1,
    cabinClass: 'economy',
    aircraft: 'Airbus A320',
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'Los Angeles International Airport',
    departureTerminal: '5',
    arrivalTerminal: '3',
  },
  {
    id: '7',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '2024-01-15T06:00:00Z',
    arrivalTime: '2024-01-15T09:30:00Z',
    duration: '5h 30m',
    airline: 'Southwest Airlines',
    airlineCode: 'WN',
    flightNumber: 'WN456',
    price: 220,
    currency: 'USD',
    stops: 0,
    cabinClass: 'economy',
    aircraft: 'Boeing 737-700',
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'Los Angeles International Airport',
    departureTerminal: '5',
    arrivalTerminal: '1',
  },
  {
    id: '8',
    origin: 'JFK',
    destination: 'LAX',
    departureTime: '2024-01-15T12:00:00Z',
    arrivalTime: '2024-01-15T15:30:00Z',
    duration: '5h 30m',
    airline: 'American Airlines',
    airlineCode: 'AA',
    flightNumber: 'AA456',
    price: 450,
    currency: 'USD',
    stops: 0,
    cabinClass: 'business',
    aircraft: 'Boeing 777-200',
    departureAirport: 'John F. Kennedy International Airport',
    arrivalAirport: 'Los Angeles International Airport',
    departureTerminal: '8',
    arrivalTerminal: '4',
  },
]; 